[project]
name = "openchat-exllama-runtime"
version = "1.0.0"
requires-python = "==3.12.*"
dependencies = [
    "aiofiles",
    "aiohttp",
    "async-lru",
    "fastapi-slim>=0.115",
    "flash-linear-attention>=0.5.0",
    "huggingface-hub",
    "httptools>=0.5.0",
    "jinja2>=3.0.0",
    "loguru",
    "numpy",
    "packaging",
    "pillow",
    "psutil",
    "pydantic>=2.11,<3",
    "requests",
    "rich",
    "ruamel-yaml",
    "setuptools",
    "sse-starlette>=2.2.0",
    "tokenizers>=0.21.0",
    "torch==2.9.0+cu128; sys_platform == 'linux'",
    "triton; sys_platform == 'linux'",
    "uvicorn>=0.28.1",
    "uvloop; sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
